// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import { navbtn } from "./nav-btn";

import AddressAutocompleteController from "./address_autocomplete_controller";
application.register("address-autocomplete", AddressAutocompleteController);

import CollapsableMenuController from "./collapsable_menu_controller";
application.register("collapsable-menu", CollapsableMenuController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import MapController from "./map_controller";
application.register("map", MapController);

import wizard from "./wizard";
application.register("wizard", Wizard);
